CREATE TABLE PERSON (
  PERSON_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
  FIRST_NAME varchar(255) not null,
  LAST_NAME varchar(255) not null,
  ADDRESS varchar(255) not null,
  PHONE_NUMBER varchar(255) not null,
  EMAIL varchar(255) not null
);

insert into PERSON (FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NUMBER, EMAIL) values ('', '', '', '', '');
insert into PERSON (FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NUMBER, EMAIL) values ('', '', '', '', '');
insert into PERSON (FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NUMBER, EMAIL) values ('', '', '', '', '');
insert into PERSON (FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NUMBER, EMAIL) values ('', '', '', '', '');
insert into PERSON (FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NUMBER, EMAIL) values ('', '', '', '', '');