UPDATE WIZARD AS wz SET wz.SCHOOL_ID = (
  SELECT schl.SCHOOL_ID FROM SCHOOL AS schl WHERE wz.SCHOOL = schl.NAME
)
WHERE wz.LAST_NAME = 'Potter';

UPDATE WIZARD AS wz SET wz.SCHOOL_ID = (
  SELECT schl.SCHOOL_ID FROM SCHOOL AS schl WHERE wz.SCHOOL = schl.NAME
)
WHERE wz.LAST_NAME = 'Granger';

UPDATE WIZARD AS wz SET wz.SCHOOL_ID = (
  SELECT schl.SCHOOL_ID FROM SCHOOL AS schl WHERE wz.SCHOOL = schl.NAME
)
WHERE wz.LAST_NAME = 'Weasley';

UPDATE WIZARD AS wz SET wz.SCHOOL_ID = (
  SELECT schl.SCHOOL_ID FROM SCHOOL AS schl WHERE wz.SCHOOL = schl.NAME
)
WHERE wz.LAST_NAME = 'Krum';

UPDATE WIZARD AS wz SET wz.SCHOOL_ID = (
  SELECT schl.SCHOOL_ID FROM SCHOOL AS schl WHERE wz.SCHOOL = schl.NAME
)
WHERE wz.LAST_NAME = 'Delacour';